general:
    virus_base_config: 'sars-cov-2'
    # e.g: 'hiv', 'sars-cov-2', or absent

output:
    snv: true
    local: false
    global: false
    visualization: true
    diversity: false
    QA: false
